
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May  6 2026 12:44:49 IST (May  6 2026 07:14:49 UTC)

// Verification Directory fv/muxdelay 

module muxdelay(A, B, C, S, clk, rst, Y);
  input A, B, C, S, clk, rst;
  output Y;
  wire A, B, C, S, clk, rst;
  wire Y;
  wire n_0, n_1, n_2, n_3, temp;
  wire VDD_CORE;
  wire VSS_CORE;
  wire VDDO_CORE;
  wire VSSO_CORE;
  nor2 g43__2398(.A (C), .B (temp), .Y (Y));
  dff temp_reg(.RST_N (rst), .clk (clk), .D (n_3), .out (temp));
  nand2x1 g45__5107(.A (n_2), .B (n_1), .Y (n_3));
  nand2x1 g46__6260(.A (n_0), .B (A), .Y (n_2));
  nand2x1 g47__4319(.A (B), .B (S), .Y (n_1));
  inverter g48(.IN (S), .OUT (n_0));
endmodule

