/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID server3.eced.svnit.ac.in)
#  Generated on:      Tue Jun 23 12:08:19 2026
#  Design:            mac_4x4_wrapper_chip
#  Command:           saveNetlist -includePowerGround ./Placement/mac_4x4_wrapper_chip_preCTS_withPG.v
###############################################################
*/
module buffd1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module buffd3 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dfnrq1 (
	CP, 
	D, 
	Q, 
	VSS, 
	VDD);
   input CP;
   input D;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module oan211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoi211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module an02d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module nd02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module ad01d1 (
	A, 
	B, 
	CI, 
	CO, 
	S, 
	VSS, 
	VDD);
   input A;
   input B;
   input CI;
   output CO;
   output S;
   inout VSS;
   inout VDD;
endmodule

module nd12d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module an03d1 (
	A1, 
	A2, 
	A3, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module or02d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module ah01d1 (
	A, 
	B, 
	CO, 
	S, 
	VSS, 
	VDD);
   input A;
   input B;
   output CO;
   output S;
   inout VSS;
   inout VDD;
endmodule

module oai21d1 (
	A, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nr02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oai22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module dfnrn1 (
	CP, 
	D, 
	QN, 
	VSS, 
	VDD);
   input CP;
   input D;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module inv0d1 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module an12d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module aoi22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module xr03d1 (
	A1, 
	A2, 
	A3, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dfnrb1 (
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module pc3c01 (
	CCLK, 
	CP, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input CCLK;
   output CP;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pc3d01 (
	PAD, 
	CIN, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input PAD;
   output CIN;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pc3o01 (
	I, 
	PAD, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input I;
   output PAD;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pvdi (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   inout VSS;
   inout VDDO;
   output VDD;
endmodule

module pv0i (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   output VSS;
   inout VDDO;
   inout VDD;
endmodule

module pvda (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   inout VSS;
   output VDDO;
   inout VDD;
endmodule

module pv0a (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   output VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 16 2026 17:39:12 IST (Jun 16 2026 12:09:12 UTC)
// Verification Directory fv/mac_4x4_wrapper_chip 
module mac_4x4 (
	clk, 
	rst, 
	enable, 
	a, 
	b, 
	mac_out, 
	VDD_CORE, 
	VSS_CORE);
   input clk;
   input rst;
   input enable;
   input [3:0] a;
   input [3:0] b;
   output [15:0] mac_out;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_OFN11_mac_out_pad_4;
   wire [7:0] mult_reg;
   wire [3:0] a_reg;
   wire [3:0] b_reg;
   wire add_89_32_n_2;
   wire add_89_32_n_4;
   wire add_89_32_n_6;
   wire add_89_32_n_8;
   wire add_89_32_n_10;
   wire add_89_32_n_12;
   wire add_89_32_n_14;
   wire add_89_32_n_16;
   wire add_89_32_n_18;
   wire add_89_32_n_20;
   wire add_89_32_n_22;
   wire add_89_32_n_24;
   wire add_89_32_n_26;
   wire add_89_32_n_28;
   wire add_89_32_n_31;
   wire enable_s1;
   wire enable_s2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_122;

   // Module instantiations
   buffd3 FE_OFC11_mac_out_pad_4 (
	.I(FE_OFN11_mac_out_pad_4),
	.Z(mac_out[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[7]  (
	.CP(clk),
	.D(n_93),
	.Q(mult_reg[7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[6]  (
	.CP(clk),
	.D(n_94),
	.Q(mult_reg[6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g1149__2398 (
	.A(rst),
	.B(n_91),
	.C1(n_90),
	.C2(n_82),
	.ZN(n_94), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi211d1 g1150__5107 (
	.A(rst),
	.B(n_78),
	.C1(n_90),
	.C2(n_76),
	.ZN(n_93), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[5]  (
	.CP(clk),
	.D(n_92),
	.Q(mult_reg[5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1152__6260 (
	.A1(n_34),
	.A2(n_89),
	.Z(n_92), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1153__4319 (
	.A1(n_90),
	.A2(n_82),
	.ZN(n_91), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 g1154__8428 (
	.A(n_80),
	.B(n_72),
	.CI(n_86),
	.CO(n_90),
	.S(n_89), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[4]  (
	.CP(clk),
	.D(n_88),
	.Q(mult_reg[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1156__5526 (
	.A1(n_34),
	.A2(n_87),
	.Z(n_88), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 g1157__6783 (
	.A(n_81),
	.B(n_69),
	.CI(n_83),
	.CO(n_86),
	.S(n_87), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[3]  (
	.CP(clk),
	.D(n_85),
	.Q(mult_reg[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1159__3680 (
	.A1(n_34),
	.A2(n_84),
	.Z(n_85), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 g1160__1617 (
	.A(n_77),
	.B(n_67),
	.CI(n_70),
	.CO(n_83),
	.S(n_84), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[2]  (
	.CP(clk),
	.D(n_79),
	.Q(mult_reg[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 g1162__2802 (
	.A(n_65),
	.B(n_53),
	.CI(n_63),
	.CO(n_80),
	.S(n_81), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1163__1705 (
	.A1(n_78),
	.A2(n_76),
	.ZN(n_82), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g1164__5122 (
	.A(rst),
	.B(n_75),
	.C1(n_73),
	.C2(n_60),
	.ZN(n_79), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an03d1 g1165__8246 (
	.A1(n_74),
	.A2(a_reg[3]),
	.A3(b_reg[3]),
	.Z(n_78), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1166__7098 (
	.A1(n_71),
	.A2(n_60),
	.ZN(n_77), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1167__6131 (
	.A1(n_73),
	.A2(n_60),
	.ZN(n_75), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 g1168__1881 (
	.A1(n_74),
	.A2(b_reg[3]),
	.Z(n_76), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 g1169__5115 (
	.A(n_47),
	.B(n_52),
	.CI(n_61),
	.CO(n_74),
	.S(n_72), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g1170__7482 (
	.A(n_68),
	.B(n_50),
	.CO(n_71),
	.S(n_73), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 g1171__4733 (
	.A(n_46),
	.B(n_54),
	.CI(n_66),
	.CO(n_69),
	.S(n_70), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[1]  (
	.CP(clk),
	.D(n_64),
	.Q(mult_reg[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g1173__6161 (
	.A(n_49),
	.B(n_56),
	.CO(n_67),
	.S(n_68), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g1174__9315 (
	.A(n_48),
	.B(n_55),
	.CO(n_65),
	.S(n_66), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an03d1 g1175__9945 (
	.A1(n_34),
	.A2(n_60),
	.A3(n_59),
	.Z(n_64), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \mult_reg_reg[0]  (
	.CP(clk),
	.D(n_62),
	.Q(mult_reg[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai21d1 g1177__2883 (
	.A(n_61),
	.B1(n_33),
	.B2(n_58),
	.ZN(n_63), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1179__2346 (
	.A1(n_51),
	.A2(rst),
	.ZN(n_62), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai22d1 g1180__1666 (
	.A1(a_reg[1]),
	.A2(b_reg[0]),
	.B1(a_reg[0]),
	.B2(b_reg[1]),
	.ZN(n_59), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1181__7410 (
	.A1(n_33),
	.A2(n_58),
	.ZN(n_61), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1182__6417 (
	.A1(n_51),
	.A2(n_50),
	.ZN(n_60), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1183__5477 (
	.A1(enable_s1),
	.A2(rst),
	.ZN(n_57), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1184__2398 (
	.A1(n_45),
	.A2(n_44),
	.ZN(n_58), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1185__5107 (
	.A1(a_reg[0]),
	.A2(b_reg[2]),
	.ZN(n_56), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1186__6260 (
	.A1(b_reg[0]),
	.A2(a_reg[3]),
	.ZN(n_55), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1187__4319 (
	.A1(a_reg[0]),
	.A2(b_reg[3]),
	.ZN(n_54), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1188__8428 (
	.A1(a_reg[1]),
	.A2(b_reg[3]),
	.ZN(n_53), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1189__5526 (
	.A1(b_reg[3]),
	.A2(n_44),
	.ZN(n_52), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 g1191__6783 (
	.A1(a_reg[0]),
	.A2(b_reg[0]),
	.Z(n_51), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1192__3680 (
	.A1(a_reg[2]),
	.A2(b_reg[0]),
	.ZN(n_49), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1193__1617 (
	.A1(a_reg[1]),
	.A2(b_reg[1]),
	.ZN(n_50), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1194__2802 (
	.A1(a_reg[2]),
	.A2(b_reg[1]),
	.ZN(n_48), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1195__1705 (
	.A1(n_45),
	.A2(a_reg[3]),
	.ZN(n_47), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1196__5122 (
	.A1(a_reg[1]),
	.A2(b_reg[2]),
	.ZN(n_46), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrn1 enable_s1_reg (
	.CP(clk),
	.D(n_40),
	.QN(enable_s1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrn1 \b_reg_reg[1]  (
	.CP(clk),
	.D(n_41),
	.QN(b_reg[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrn1 \a_reg_reg[1]  (
	.CP(clk),
	.D(n_36),
	.QN(a_reg[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[3]  (
	.CP(clk),
	.D(n_37),
	.Q(b_reg[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrn1 \a_reg_reg[0]  (
	.CP(clk),
	.D(n_38),
	.QN(a_reg[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \a_reg_reg[3]  (
	.CP(clk),
	.D(n_43),
	.Q(a_reg[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrn1 \b_reg_reg[0]  (
	.CP(clk),
	.D(n_39),
	.QN(b_reg[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1209__8246 (
	.A1(n_34),
	.A2(a[3]),
	.Z(n_43), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1210__7098 (
	.A1(n_34),
	.A2(b[2]),
	.Z(n_42), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1211__6131 (
	.A1(n_34),
	.A2(b[1]),
	.Z(n_41), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1212__1881 (
	.A1(n_34),
	.A2(enable),
	.Z(n_40), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1213__5115 (
	.A1(n_34),
	.A2(b[0]),
	.Z(n_39), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1214__7482 (
	.A1(n_34),
	.A2(a[0]),
	.Z(n_38), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1215__4733 (
	.A1(n_34),
	.A2(b[3]),
	.Z(n_37), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1216__6161 (
	.A1(n_34),
	.A2(a[1]),
	.Z(n_36), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g1217__9315 (
	.A1(n_34),
	.A2(a[2]),
	.Z(n_35), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d1 g1218 (
	.I(rst),
	.ZN(n_34), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an12d1 g2__9945 (
	.A1(b_reg[1]),
	.A2(a_reg[3]),
	.Z(n_33), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[7]  (
	.CP(clk),
	.D(n_31),
	.Q(mac_out[7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[1]  (
	.CP(clk),
	.D(n_26),
	.Q(mac_out[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[5]  (
	.CP(clk),
	.D(n_17),
	.Q(mac_out[5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[6]  (
	.CP(clk),
	.D(n_28),
	.Q(mac_out[6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[0]  (
	.CP(clk),
	.D(n_32),
	.Q(mac_out[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[8]  (
	.CP(clk),
	.D(n_30),
	.Q(mac_out[8]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[9]  (
	.CP(clk),
	.D(n_29),
	.Q(mac_out[9]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[10]  (
	.CP(clk),
	.D(n_27),
	.Q(mac_out[10]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[14]  (
	.CP(clk),
	.D(n_24),
	.Q(mac_out[14]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[11]  (
	.CP(clk),
	.D(n_20),
	.Q(mac_out[11]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[12]  (
	.CP(clk),
	.D(n_23),
	.Q(mac_out[12]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[13]  (
	.CP(clk),
	.D(n_21),
	.Q(mac_out[13]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[2]  (
	.CP(clk),
	.D(n_25),
	.Q(mac_out[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[3]  (
	.CP(clk),
	.D(n_22),
	.Q(mac_out[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[15]  (
	.CP(clk),
	.D(n_19),
	.Q(mac_out[15]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \acc_reg_reg[4]  (
	.CP(clk),
	.D(n_18),
	.Q(FE_OFN11_mac_out_pad_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g662__2883 (
	.A1(n_13),
	.A2(rst),
	.ZN(n_32), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g663__2346 (
	.A1(n_15),
	.A2(rst),
	.ZN(n_31), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g664__1666 (
	.A1(n_14),
	.A2(rst),
	.ZN(n_30), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g665__7410 (
	.A1(n_16),
	.A2(rst),
	.ZN(n_29), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g666__6417 (
	.A1(n_12),
	.A2(rst),
	.ZN(n_28), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g667__5477 (
	.A1(n_10),
	.A2(rst),
	.ZN(n_27), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g668__2398 (
	.A1(n_11),
	.A2(rst),
	.ZN(n_26), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g669__5107 (
	.A1(n_5),
	.A2(rst),
	.ZN(n_25), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g670__6260 (
	.A1(n_8),
	.A2(rst),
	.ZN(n_24), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g671__4319 (
	.A1(n_4),
	.A2(rst),
	.ZN(n_23), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g672__8428 (
	.A1(n_6),
	.A2(rst),
	.ZN(n_22), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g673__5526 (
	.A1(n_7),
	.A2(rst),
	.ZN(n_21), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g674__6783 (
	.A1(n_9),
	.A2(rst),
	.ZN(n_20), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g675__3680 (
	.A1(n_3),
	.A2(rst),
	.ZN(n_19), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g676__1617 (
	.A1(n_2),
	.A2(rst),
	.ZN(n_18), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g677__2802 (
	.A1(n_1),
	.A2(rst),
	.ZN(n_17), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g678__1705 (
	.A1(mac_out[9]),
	.A2(n_0),
	.B1(n_110),
	.B2(enable_s2),
	.ZN(n_16), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g679__5122 (
	.A1(mac_out[7]),
	.A2(n_0),
	.B1(n_112),
	.B2(enable_s2),
	.ZN(n_15), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g680__8246 (
	.A1(mac_out[8]),
	.A2(n_0),
	.B1(n_111),
	.B2(enable_s2),
	.ZN(n_14), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g681__7098 (
	.A1(mac_out[0]),
	.A2(n_0),
	.B1(n_119),
	.B2(enable_s2),
	.ZN(n_13), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g682__6131 (
	.A1(mac_out[6]),
	.A2(n_0),
	.B1(n_113),
	.B2(enable_s2),
	.ZN(n_12), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g683__1881 (
	.A1(mac_out[1]),
	.A2(n_0),
	.B1(n_118),
	.B2(enable_s2),
	.ZN(n_11), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g684__5115 (
	.A1(mac_out[10]),
	.A2(n_0),
	.B1(n_109),
	.B2(enable_s2),
	.ZN(n_10), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g685__7482 (
	.A1(mac_out[11]),
	.A2(n_0),
	.B1(n_108),
	.B2(enable_s2),
	.ZN(n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g686__4733 (
	.A1(mac_out[14]),
	.A2(n_0),
	.B1(n_105),
	.B2(enable_s2),
	.ZN(n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g687__6161 (
	.A1(mac_out[13]),
	.A2(n_0),
	.B1(n_106),
	.B2(enable_s2),
	.ZN(n_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g688__9315 (
	.A1(mac_out[3]),
	.A2(n_0),
	.B1(n_116),
	.B2(enable_s2),
	.ZN(n_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g689__9945 (
	.A1(mac_out[2]),
	.A2(n_0),
	.B1(n_117),
	.B2(enable_s2),
	.ZN(n_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g690__2883 (
	.A1(mac_out[12]),
	.A2(n_0),
	.B1(n_107),
	.B2(enable_s2),
	.ZN(n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g691__2346 (
	.A1(mac_out[15]),
	.A2(n_0),
	.B1(n_122),
	.B2(enable_s2),
	.ZN(n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g692__1666 (
	.A1(mac_out[4]),
	.A2(n_0),
	.B1(n_115),
	.B2(enable_s2),
	.ZN(n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g693__7410 (
	.A1(mac_out[5]),
	.A2(n_0),
	.B1(n_114),
	.B2(enable_s2),
	.ZN(n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g369__5477 (
	.A(mac_out[14]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_28),
	.CO(add_89_32_n_31),
	.S(n_105), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g370__2398 (
	.A(mac_out[13]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_26),
	.CO(add_89_32_n_28),
	.S(n_106), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g371__5107 (
	.A(mac_out[12]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_24),
	.CO(add_89_32_n_26),
	.S(n_107), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g372__6260 (
	.A(mac_out[11]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_22),
	.CO(add_89_32_n_24),
	.S(n_108), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g373__4319 (
	.A(mac_out[10]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_20),
	.CO(add_89_32_n_22),
	.S(n_109), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g374__8428 (
	.A(mac_out[9]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_18),
	.CO(add_89_32_n_20),
	.S(n_110), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g375__5526 (
	.A(mac_out[8]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_16),
	.CO(add_89_32_n_18),
	.S(n_111), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g376__6783 (
	.A(mac_out[7]),
	.B(mult_reg[7]),
	.CI(add_89_32_n_14),
	.CO(add_89_32_n_16),
	.S(n_112), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g377__3680 (
	.A(mac_out[6]),
	.B(mult_reg[6]),
	.CI(add_89_32_n_12),
	.CO(add_89_32_n_14),
	.S(n_113), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g378__1617 (
	.A(mac_out[5]),
	.B(mult_reg[5]),
	.CI(add_89_32_n_10),
	.CO(add_89_32_n_12),
	.S(n_114), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g379__2802 (
	.A(mac_out[4]),
	.B(mult_reg[4]),
	.CI(add_89_32_n_8),
	.CO(add_89_32_n_10),
	.S(n_115), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g380__1705 (
	.A(mac_out[3]),
	.B(mult_reg[3]),
	.CI(add_89_32_n_6),
	.CO(add_89_32_n_8),
	.S(n_116), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g381__5122 (
	.A(mac_out[2]),
	.B(mult_reg[2]),
	.CI(add_89_32_n_4),
	.CO(add_89_32_n_6),
	.S(n_117), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_89_32_g382__8246 (
	.A(mac_out[1]),
	.B(mult_reg[1]),
	.CI(add_89_32_n_2),
	.CO(add_89_32_n_4),
	.S(n_118), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 add_89_32_g383__7098 (
	.A(mac_out[0]),
	.B(mult_reg[0]),
	.CO(add_89_32_n_2),
	.S(n_119), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr03d1 g2 (
	.A1(add_89_32_n_31),
	.A2(mac_out[15]),
	.A3(mult_reg[7]),
	.Z(n_122), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrb1 \b_reg_reg[2]  (
	.CP(clk),
	.D(n_42),
	.Q(n_45),
	.QN(b_reg[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrb1 \a_reg_reg[2]  (
	.CP(clk),
	.D(n_35),
	.Q(n_44),
	.QN(a_reg[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrb1 enable_s2_reg (
	.CP(clk),
	.D(n_57),
	.Q(enable_s2),
	.QN(n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module mac_4x4_wrapper_chip (
	clk, 
	rst, 
	enable, 
	a, 
	b, 
	mac_out);
   input clk;
   input rst;
   input enable;
   input [3:0] a;
   input [3:0] b;
   output [15:0] mac_out;

   // Internal wires
   wire FE_OFN13_mac_out_pad_15;
   wire FE_OFN12_mac_out_pad_14;
   wire FE_OFN10_mac_out_pad_5;
   wire FE_OFN9_mac_out_pad_6;
   wire FE_OFN8_mac_out_pad_7;
   wire FE_OFN7_mac_out_pad_8;
   wire FE_OFN6_mac_out_pad_9;
   wire FE_OFN5_mac_out_pad_10;
   wire FE_OFN4_mac_out_pad_11;
   wire FE_OFN3_mac_out_pad_12;
   wire FE_OFN2_mac_out_pad_13;
   wire [3:0] a_pad;
   wire [3:0] b_pad;
   wire [15:0] mac_out_pad;
   wire clk_buf;
   wire clk_pad;
   wire enable_pad;
   wire rst_pad;
   wire VDD_CORE;
   wire VSS_CORE;
   wire VDDO_CORE;
   wire VSSO_CORE;

   // Module instantiations
   buffd1 FE_OFC13_mac_out_pad_15 (
	.I(mac_out_pad[15]),
	.Z(FE_OFN13_mac_out_pad_15), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC12_mac_out_pad_14 (
	.I(mac_out_pad[14]),
	.Z(FE_OFN12_mac_out_pad_14), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC10_mac_out_pad_5 (
	.I(mac_out_pad[5]),
	.Z(FE_OFN10_mac_out_pad_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC9_mac_out_pad_6 (
	.I(mac_out_pad[6]),
	.Z(FE_OFN9_mac_out_pad_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC8_mac_out_pad_7 (
	.I(mac_out_pad[7]),
	.Z(FE_OFN8_mac_out_pad_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC7_mac_out_pad_8 (
	.I(mac_out_pad[8]),
	.Z(FE_OFN7_mac_out_pad_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC6_mac_out_pad_9 (
	.I(mac_out_pad[9]),
	.Z(FE_OFN6_mac_out_pad_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC5_mac_out_pad_10 (
	.I(mac_out_pad[10]),
	.Z(FE_OFN5_mac_out_pad_10), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC4_mac_out_pad_11 (
	.I(mac_out_pad[11]),
	.Z(FE_OFN4_mac_out_pad_11), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC3_mac_out_pad_12 (
	.I(mac_out_pad[12]),
	.Z(FE_OFN3_mac_out_pad_12), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_OFC2_mac_out_pad_13 (
	.I(mac_out_pad[13]),
	.Z(FE_OFN2_mac_out_pad_13), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mac_4x4 dut (
	.clk(clk_buf),
	.rst(rst_pad),
	.enable(enable_pad),
	.a(a_pad),
	.b(b_pad),
	.mac_out(mac_out_pad), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   pc3c01 pc3c01_clk_buf (
	.CCLK(clk_pad),
	.CP(clk_buf), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_a0 (
	.PAD(a[0]),
	.CIN(a_pad[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_a1 (
	.PAD(a[1]),
	.CIN(a_pad[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_a2 (
	.PAD(a[2]),
	.CIN(a_pad[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_a3 (
	.PAD(a[3]),
	.CIN(a_pad[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_b0 (
	.PAD(b[0]),
	.CIN(b_pad[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_b1 (
	.PAD(b[1]),
	.CIN(b_pad[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_b2 (
	.PAD(b[2]),
	.CIN(b_pad[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_b3 (
	.PAD(b[3]),
	.CIN(b_pad[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_clk (
	.PAD(clk),
	.CIN(clk_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_enable (
	.PAD(enable),
	.CIN(enable_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_rst (
	.PAD(rst),
	.CIN(rst_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out0 (
	.I(mac_out_pad[0]),
	.PAD(mac_out[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out1 (
	.I(mac_out_pad[1]),
	.PAD(mac_out[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out2 (
	.I(mac_out_pad[2]),
	.PAD(mac_out[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out3 (
	.I(mac_out_pad[3]),
	.PAD(mac_out[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out4 (
	.I(mac_out_pad[4]),
	.PAD(mac_out[4]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out5 (
	.I(FE_OFN10_mac_out_pad_5),
	.PAD(mac_out[5]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out6 (
	.I(FE_OFN9_mac_out_pad_6),
	.PAD(mac_out[6]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out7 (
	.I(FE_OFN8_mac_out_pad_7),
	.PAD(mac_out[7]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out8 (
	.I(FE_OFN7_mac_out_pad_8),
	.PAD(mac_out[8]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out9 (
	.I(FE_OFN6_mac_out_pad_9),
	.PAD(mac_out[9]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out10 (
	.I(FE_OFN5_mac_out_pad_10),
	.PAD(mac_out[10]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out11 (
	.I(FE_OFN4_mac_out_pad_11),
	.PAD(mac_out[11]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out12 (
	.I(FE_OFN3_mac_out_pad_12),
	.PAD(mac_out[12]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out13 (
	.I(FE_OFN2_mac_out_pad_13),
	.PAD(mac_out[13]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out14 (
	.I(FE_OFN12_mac_out_pad_14),
	.PAD(mac_out[14]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_mac_out15 (
	.I(FE_OFN13_mac_out_pad_15),
	.PAD(mac_out[15]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy4 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
endmodule

