###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID server3.eced.svnit.ac.in)
#  Generated on:      Tue Jun 23 12:11:57 2026
#  Design:            mac_4x4_wrapper_chip
#  Command:           create_ccopt_clock_tree_spec -file ./ClockTreeSynthesis/mac_4x4_wrapper_chip_ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 200.000ns) in timing_config all([top_streamed_wrapper_chip_sdc.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 200

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:all (sdc top_streamed_wrapper_chip_sdc.sdc)
create_ccopt_skew_group -name clk/all -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/all true
set_ccopt_property extracted_from_clock_name -skew_group clk/all clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/all all
set_ccopt_property extracted_from_delay_corners -skew_group clk/all {max_delay min_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

