/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID server3.eced.svnit.ac.in)
#  Generated on:      Tue Jun 23 12:12:58 2026
#  Design:            mac_4x4_wrapper_chip
#  Command:           saveNetlist ./ClockTreeSynthesis/top_chip_wrapper_postCTS_withoutPG.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 16 2026 17:39:12 IST (Jun 16 2026 12:09:12 UTC)
// Verification Directory fv/mac_4x4_wrapper_chip 
module mac_4x4 (
	clk, 
	rst, 
	enable, 
	a, 
	b, 
	mac_out);
   input clk;
   input rst;
   input enable;
   input [3:0] a;
   input [3:0] b;
   output [15:0] mac_out;

   // Internal wires
   wire FE_PHN132_n_15;
   wire FE_PHN131_n_4;
   wire FE_PHN130_n_10;
   wire FE_PHN129_n_16;
   wire FE_PHN128_n_9;
   wire FE_PHN127_n_14;
   wire FE_PHN126_n_7;
   wire FE_PHN125_n_1;
   wire FE_PHN124_n_12;
   wire FE_PHN123_n_2;
   wire FE_PHN122_n_8;
   wire FE_PHN121_n_3;
   wire FE_PHN120_n_89;
   wire FE_PHN119_n_87;
   wire FE_PHN118_n_94;
   wire FE_PHN117_n_64;
   wire FE_PHN116_n_93;
   wire FE_PHN115_n_51;
   wire FE_PHN114_n_11;
   wire FE_PHN113_n_13;
   wire FE_PHN112_enable_s1;
   wire FE_PHN102_mac_out_pad_3;
   wire FE_PHN101_mac_out_pad_2;
   wire FE_PHN100_a_reg_3;
   wire FE_PHN99_a_reg_2;
   wire FE_PHN98_b_reg_3;
   wire FE_PHN97_b_reg_2;
   wire FE_PHN96_mult_reg_4;
   wire FE_PHN95_mult_reg_3;
   wire FE_PHN94_mult_reg_2;
   wire FE_PHN93_n_2;
   wire FE_PHN92_n_3;
   wire FE_PHN91_n_12;
   wire FE_PHN90_n_5;
   wire FE_PHN89_n_8;
   wire FE_PHN88_n_1;
   wire FE_PHN87_n_84;
   wire FE_PHN86_n_87;
   wire FE_PHN85_n_6;
   wire FE_PHN84_n_14;
   wire FE_PHN83_n_89;
   wire FE_PHN82_n_9;
   wire FE_PHN81_n_16;
   wire FE_PHN80_n_7;
   wire FE_PHN79_n_93;
   wire FE_PHN78_n_79;
   wire FE_PHN77_n_94;
   wire FE_PHN76_n_15;
   wire FE_PHN75_n_4;
   wire FE_PHN74_n_10;
   wire FE_PHN73_a_pad_1;
   wire FE_PHN72_enable_pad;
   wire FE_PHN71_b_pad_1;
   wire FE_PHN70_b_pad_0;
   wire FE_PHN69_a_pad_3;
   wire FE_PHN68_a_pad_2;
   wire FE_PHN67_a_pad_0;
   wire FE_PHN66_b_pad_3;
   wire FE_PHN65_b_pad_2;
   wire FE_PHN64_enable_s1;
   wire FE_PHN63_mult_reg_7;
   wire FE_PHN62_n_0;
   wire FE_PHN61_mult_reg_1;
   wire FE_PHN60_mac_out_pad_0;
   wire FE_PHN59_mac_out_pad_1;
   wire FE_PHN58_enable_s2;
   wire FE_PHN57_mult_reg_0;
   wire FE_PHN56_a_reg_1;
   wire FE_PHN55_a_reg_0;
   wire FE_PHN54_b_reg_1;
   wire FE_PHN53_b_reg_0;
   wire FE_PHN52_n_40;
   wire FE_PHN51_n_42;
   wire FE_PHN50_n_41;
   wire FE_PHN49_n_37;
   wire FE_PHN48_n_39;
   wire FE_PHN47_n_43;
   wire FE_PHN46_n_57;
   wire FE_PHN45_n_38;
   wire FE_PHN44_n_88;
   wire FE_PHN43_n_23;
   wire FE_PHN42_n_92;
   wire FE_PHN41_n_85;
   wire FE_PHN40_n_27;
   wire FE_PHN39_n_29;
   wire FE_PHN38_n_35;
   wire FE_PHN37_n_36;
   wire FE_PHN36_n_79;
   wire FE_PHN35_n_28;
   wire FE_PHN34_n_22;
   wire FE_PHN33_n_31;
   wire FE_PHN32_n_25;
   wire FE_PHN31_n_21;
   wire FE_PHN30_n_94;
   wire FE_PHN29_n_24;
   wire FE_PHN28_n_93;
   wire FE_PHN27_n_18;
   wire FE_PHN26_n_30;
   wire FE_PHN25_n_20;
   wire FE_PHN24_n_19;
   wire FE_PHN23_n_17;
   wire FE_PHN22_mult_reg_0;
   wire FE_PHN21_mult_reg_1;
   wire FE_PHN20_mac_out_pad_0;
   wire FE_PHN19_mac_out_pad_1;
   wire FE_PHN18_enable_s2;
   wire FE_PHN17_n_0;
   wire FE_PHN16_a_reg_0;
   wire FE_PHN15_a_reg_1;
   wire FE_PHN14_b_reg_0;
   wire FE_PHN13_b_reg_1;
   wire FE_OFN11_mac_out_pad_4;
   wire [7:0] mult_reg;
   wire [3:0] a_reg;
   wire [3:0] b_reg;
   wire add_89_32_n_2;
   wire add_89_32_n_4;
   wire add_89_32_n_6;
   wire add_89_32_n_8;
   wire add_89_32_n_10;
   wire add_89_32_n_12;
   wire add_89_32_n_14;
   wire add_89_32_n_16;
   wire add_89_32_n_18;
   wire add_89_32_n_20;
   wire add_89_32_n_22;
   wire add_89_32_n_24;
   wire add_89_32_n_26;
   wire add_89_32_n_28;
   wire add_89_32_n_31;
   wire enable_s1;
   wire enable_s2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_122;

   dl04d1 FE_PHC132_n_15 (.I(n_15),
	.Z(FE_PHN132_n_15));
   dl04d1 FE_PHC131_n_4 (.I(n_4),
	.Z(FE_PHN131_n_4));
   dl04d1 FE_PHC130_n_10 (.I(n_10),
	.Z(FE_PHN130_n_10));
   dl04d1 FE_PHC129_n_16 (.I(n_16),
	.Z(FE_PHN129_n_16));
   dl04d1 FE_PHC128_n_9 (.I(n_9),
	.Z(FE_PHN128_n_9));
   dl04d1 FE_PHC127_n_14 (.I(n_14),
	.Z(FE_PHN127_n_14));
   dl04d1 FE_PHC126_n_7 (.I(n_7),
	.Z(FE_PHN126_n_7));
   dl04d1 FE_PHC125_n_1 (.I(n_1),
	.Z(FE_PHN125_n_1));
   dl04d1 FE_PHC124_n_12 (.I(n_12),
	.Z(FE_PHN124_n_12));
   dl04d1 FE_PHC123_n_2 (.I(n_2),
	.Z(FE_PHN123_n_2));
   dl04d1 FE_PHC122_n_8 (.I(n_8),
	.Z(FE_PHN122_n_8));
   dl04d1 FE_PHC121_n_3 (.I(n_3),
	.Z(FE_PHN121_n_3));
   dl04d1 FE_PHC120_n_89 (.I(n_89),
	.Z(FE_PHN120_n_89));
   dl04d1 FE_PHC119_n_87 (.I(n_87),
	.Z(FE_PHN119_n_87));
   dl04d1 FE_PHC118_n_94 (.I(n_94),
	.Z(FE_PHN118_n_94));
   dl04d1 FE_PHC117_n_64 (.I(n_64),
	.Z(FE_PHN117_n_64));
   dl04d1 FE_PHC116_n_93 (.I(n_93),
	.Z(FE_PHN116_n_93));
   dl04d1 FE_PHC115_n_51 (.I(n_51),
	.Z(FE_PHN115_n_51));
   dl04d1 FE_PHC114_n_11 (.I(n_11),
	.Z(FE_PHN114_n_11));
   dl04d1 FE_PHC113_n_13 (.I(n_13),
	.Z(FE_PHN113_n_13));
   dl04d1 FE_PHC112_enable_s1 (.I(enable_s1),
	.Z(FE_PHN112_enable_s1));
   dl04d1 FE_PHC102_mac_out_pad_3 (.I(mac_out[3]),
	.Z(FE_PHN102_mac_out_pad_3));
   dl04d1 FE_PHC101_mac_out_pad_2 (.I(mac_out[2]),
	.Z(FE_PHN101_mac_out_pad_2));
   dl04d1 FE_PHC100_a_reg_3 (.I(a_reg[3]),
	.Z(FE_PHN100_a_reg_3));
   dl04d1 FE_PHC99_a_reg_2 (.I(a_reg[2]),
	.Z(FE_PHN99_a_reg_2));
   dl04d1 FE_PHC98_b_reg_3 (.I(b_reg[3]),
	.Z(FE_PHN98_b_reg_3));
   dl04d1 FE_PHC97_b_reg_2 (.I(b_reg[2]),
	.Z(FE_PHN97_b_reg_2));
   dl04d1 FE_PHC96_mult_reg_4 (.I(mult_reg[4]),
	.Z(FE_PHN96_mult_reg_4));
   dl04d1 FE_PHC95_mult_reg_3 (.I(mult_reg[3]),
	.Z(FE_PHN95_mult_reg_3));
   dl04d1 FE_PHC94_mult_reg_2 (.I(mult_reg[2]),
	.Z(FE_PHN94_mult_reg_2));
   dl04d1 FE_PHC93_n_2 (.I(FE_PHN123_n_2),
	.Z(FE_PHN93_n_2));
   dl04d1 FE_PHC92_n_3 (.I(FE_PHN121_n_3),
	.Z(FE_PHN92_n_3));
   dl04d1 FE_PHC91_n_12 (.I(FE_PHN124_n_12),
	.Z(FE_PHN91_n_12));
   dl04d1 FE_PHC90_n_5 (.I(n_5),
	.Z(FE_PHN90_n_5));
   dl04d1 FE_PHC89_n_8 (.I(FE_PHN122_n_8),
	.Z(FE_PHN89_n_8));
   dl04d1 FE_PHC88_n_1 (.I(FE_PHN125_n_1),
	.Z(FE_PHN88_n_1));
   dl04d1 FE_PHC87_n_84 (.I(n_84),
	.Z(FE_PHN87_n_84));
   dl04d1 FE_PHC86_n_87 (.I(FE_PHN119_n_87),
	.Z(FE_PHN86_n_87));
   dl04d1 FE_PHC85_n_6 (.I(n_6),
	.Z(FE_PHN85_n_6));
   dl04d1 FE_PHC84_n_14 (.I(FE_PHN127_n_14),
	.Z(FE_PHN84_n_14));
   dl04d1 FE_PHC83_n_89 (.I(FE_PHN120_n_89),
	.Z(FE_PHN83_n_89));
   dl04d1 FE_PHC82_n_9 (.I(FE_PHN128_n_9),
	.Z(FE_PHN82_n_9));
   dl04d1 FE_PHC81_n_16 (.I(FE_PHN129_n_16),
	.Z(FE_PHN81_n_16));
   dl04d1 FE_PHC80_n_7 (.I(FE_PHN126_n_7),
	.Z(FE_PHN80_n_7));
   dl04d1 FE_PHC79_n_93 (.I(FE_PHN116_n_93),
	.Z(FE_PHN79_n_93));
   dl04d1 FE_PHC78_n_79 (.I(n_79),
	.Z(FE_PHN78_n_79));
   dl04d1 FE_PHC77_n_94 (.I(FE_PHN118_n_94),
	.Z(FE_PHN77_n_94));
   dl04d1 FE_PHC76_n_15 (.I(FE_PHN132_n_15),
	.Z(FE_PHN76_n_15));
   dl04d1 FE_PHC75_n_4 (.I(FE_PHN131_n_4),
	.Z(FE_PHN75_n_4));
   dl04d1 FE_PHC74_n_10 (.I(FE_PHN130_n_10),
	.Z(FE_PHN74_n_10));
   dl04d1 FE_PHC73_a_pad_1 (.I(a[1]),
	.Z(FE_PHN73_a_pad_1));
   dl04d1 FE_PHC72_enable_pad (.I(enable),
	.Z(FE_PHN72_enable_pad));
   dl04d1 FE_PHC71_b_pad_1 (.I(b[1]),
	.Z(FE_PHN71_b_pad_1));
   dl04d1 FE_PHC70_b_pad_0 (.I(b[0]),
	.Z(FE_PHN70_b_pad_0));
   dl04d1 FE_PHC69_a_pad_3 (.I(a[3]),
	.Z(FE_PHN69_a_pad_3));
   dl04d1 FE_PHC68_a_pad_2 (.I(a[2]),
	.Z(FE_PHN68_a_pad_2));
   dl04d1 FE_PHC67_a_pad_0 (.I(a[0]),
	.Z(FE_PHN67_a_pad_0));
   dl04d1 FE_PHC66_b_pad_3 (.I(b[3]),
	.Z(FE_PHN66_b_pad_3));
   dl04d1 FE_PHC65_b_pad_2 (.I(b[2]),
	.Z(FE_PHN65_b_pad_2));
   dl04d1 FE_PHC64_enable_s1 (.I(FE_PHN112_enable_s1),
	.Z(FE_PHN64_enable_s1));
   dl04d2 FE_PHC63_mult_reg_7 (.I(mult_reg[7]),
	.Z(FE_PHN63_mult_reg_7));
   dl04d1 FE_PHC62_n_0 (.I(n_0),
	.Z(FE_PHN62_n_0));
   dl04d1 FE_PHC61_mult_reg_1 (.I(mult_reg[1]),
	.Z(FE_PHN61_mult_reg_1));
   dl04d1 FE_PHC60_mac_out_pad_0 (.I(FE_PHN20_mac_out_pad_0),
	.Z(FE_PHN60_mac_out_pad_0));
   dl04d1 FE_PHC59_mac_out_pad_1 (.I(FE_PHN19_mac_out_pad_1),
	.Z(FE_PHN59_mac_out_pad_1));
   dl04d1 FE_PHC58_enable_s2 (.I(enable_s2),
	.Z(FE_PHN58_enable_s2));
   dl04d1 FE_PHC57_mult_reg_0 (.I(mult_reg[0]),
	.Z(FE_PHN57_mult_reg_0));
   dl04d1 FE_PHC56_a_reg_1 (.I(a_reg[1]),
	.Z(FE_PHN56_a_reg_1));
   dl04d1 FE_PHC55_a_reg_0 (.I(a_reg[0]),
	.Z(FE_PHN55_a_reg_0));
   dl04d1 FE_PHC54_b_reg_1 (.I(b_reg[1]),
	.Z(FE_PHN54_b_reg_1));
   dl04d1 FE_PHC53_b_reg_0 (.I(b_reg[0]),
	.Z(FE_PHN53_b_reg_0));
   dl04d1 FE_PHC52_n_40 (.I(n_40),
	.Z(FE_PHN52_n_40));
   dl04d1 FE_PHC51_n_42 (.I(n_42),
	.Z(FE_PHN51_n_42));
   dl04d1 FE_PHC50_n_41 (.I(n_41),
	.Z(FE_PHN50_n_41));
   dl04d1 FE_PHC49_n_37 (.I(n_37),
	.Z(FE_PHN49_n_37));
   dl04d1 FE_PHC48_n_39 (.I(n_39),
	.Z(FE_PHN48_n_39));
   dl04d1 FE_PHC47_n_43 (.I(n_43),
	.Z(FE_PHN47_n_43));
   dl04d1 FE_PHC46_n_57 (.I(n_57),
	.Z(FE_PHN46_n_57));
   dl04d1 FE_PHC45_n_38 (.I(n_38),
	.Z(FE_PHN45_n_38));
   dl04d1 FE_PHC44_n_88 (.I(n_88),
	.Z(FE_PHN44_n_88));
   dl04d1 FE_PHC43_n_23 (.I(n_23),
	.Z(FE_PHN43_n_23));
   dl04d1 FE_PHC42_n_92 (.I(n_92),
	.Z(FE_PHN42_n_92));
   dl04d1 FE_PHC41_n_85 (.I(n_85),
	.Z(FE_PHN41_n_85));
   dl04d1 FE_PHC40_n_27 (.I(n_27),
	.Z(FE_PHN40_n_27));
   dl04d1 FE_PHC39_n_29 (.I(n_29),
	.Z(FE_PHN39_n_29));
   dl04d1 FE_PHC38_n_35 (.I(n_35),
	.Z(FE_PHN38_n_35));
   dl04d1 FE_PHC37_n_36 (.I(n_36),
	.Z(FE_PHN37_n_36));
   dl04d1 FE_PHC36_n_79 (.I(FE_PHN78_n_79),
	.Z(FE_PHN36_n_79));
   dl04d1 FE_PHC35_n_28 (.I(n_28),
	.Z(FE_PHN35_n_28));
   dl04d1 FE_PHC34_n_22 (.I(n_22),
	.Z(FE_PHN34_n_22));
   dl04d1 FE_PHC33_n_31 (.I(n_31),
	.Z(FE_PHN33_n_31));
   dl04d1 FE_PHC32_n_25 (.I(n_25),
	.Z(FE_PHN32_n_25));
   dl04d1 FE_PHC31_n_21 (.I(n_21),
	.Z(FE_PHN31_n_21));
   dl04d1 FE_PHC30_n_94 (.I(FE_PHN77_n_94),
	.Z(FE_PHN30_n_94));
   dl04d1 FE_PHC29_n_24 (.I(n_24),
	.Z(FE_PHN29_n_24));
   dl04d1 FE_PHC28_n_93 (.I(FE_PHN79_n_93),
	.Z(FE_PHN28_n_93));
   dl04d1 FE_PHC27_n_18 (.I(n_18),
	.Z(FE_PHN27_n_18));
   dl04d1 FE_PHC26_n_30 (.I(n_30),
	.Z(FE_PHN26_n_30));
   dl04d1 FE_PHC25_n_20 (.I(n_20),
	.Z(FE_PHN25_n_20));
   dl04d1 FE_PHC24_n_19 (.I(n_19),
	.Z(FE_PHN24_n_19));
   dl04d1 FE_PHC23_n_17 (.I(n_17),
	.Z(FE_PHN23_n_17));
   dl04d1 FE_PHC22_mult_reg_0 (.I(FE_PHN57_mult_reg_0),
	.Z(FE_PHN22_mult_reg_0));
   dl04d1 FE_PHC21_mult_reg_1 (.I(FE_PHN61_mult_reg_1),
	.Z(FE_PHN21_mult_reg_1));
   dl04d1 FE_PHC20_mac_out_pad_0 (.I(mac_out[0]),
	.Z(FE_PHN20_mac_out_pad_0));
   dl04d1 FE_PHC19_mac_out_pad_1 (.I(mac_out[1]),
	.Z(FE_PHN19_mac_out_pad_1));
   dl04d1 FE_PHC18_enable_s2 (.I(FE_PHN58_enable_s2),
	.Z(FE_PHN18_enable_s2));
   dl04d1 FE_PHC17_n_0 (.I(FE_PHN62_n_0),
	.Z(FE_PHN17_n_0));
   dl04d1 FE_PHC16_a_reg_0 (.I(FE_PHN55_a_reg_0),
	.Z(FE_PHN16_a_reg_0));
   dl04d1 FE_PHC15_a_reg_1 (.I(FE_PHN56_a_reg_1),
	.Z(FE_PHN15_a_reg_1));
   dl04d1 FE_PHC14_b_reg_0 (.I(FE_PHN53_b_reg_0),
	.Z(FE_PHN14_b_reg_0));
   dl04d1 FE_PHC13_b_reg_1 (.I(FE_PHN54_b_reg_1),
	.Z(FE_PHN13_b_reg_1));
   buffd3 FE_OFC11_mac_out_pad_4 (.I(FE_OFN11_mac_out_pad_4),
	.Z(mac_out[4]));
   dfnrq1 \mult_reg_reg[7]  (.CP(clk),
	.D(FE_PHN28_n_93),
	.Q(mult_reg[7]));
   dfnrq1 \mult_reg_reg[6]  (.CP(clk),
	.D(FE_PHN30_n_94),
	.Q(mult_reg[6]));
   oan211d1 g1149__2398 (.A(rst),
	.B(n_91),
	.C1(n_90),
	.C2(n_82),
	.ZN(n_94));
   aoi211d1 g1150__5107 (.A(rst),
	.B(n_78),
	.C1(n_90),
	.C2(n_76),
	.ZN(n_93));
   dfnrq1 \mult_reg_reg[5]  (.CP(clk),
	.D(FE_PHN42_n_92),
	.Q(mult_reg[5]));
   an02d1 g1152__6260 (.A1(n_34),
	.A2(FE_PHN83_n_89),
	.Z(n_92));
   nd02d1 g1153__4319 (.A1(n_90),
	.A2(n_82),
	.ZN(n_91));
   ad01d1 g1154__8428 (.A(n_80),
	.B(n_72),
	.CI(n_86),
	.CO(n_90),
	.S(n_89));
   dfnrq1 \mult_reg_reg[4]  (.CP(clk),
	.D(FE_PHN44_n_88),
	.Q(mult_reg[4]));
   an02d1 g1156__5526 (.A1(n_34),
	.A2(FE_PHN86_n_87),
	.Z(n_88));
   ad01d1 g1157__6783 (.A(n_81),
	.B(n_69),
	.CI(n_83),
	.CO(n_86),
	.S(n_87));
   dfnrq1 \mult_reg_reg[3]  (.CP(clk),
	.D(FE_PHN41_n_85),
	.Q(mult_reg[3]));
   an02d1 g1159__3680 (.A1(n_34),
	.A2(FE_PHN87_n_84),
	.Z(n_85));
   ad01d1 g1160__1617 (.A(n_77),
	.B(n_67),
	.CI(n_70),
	.CO(n_83),
	.S(n_84));
   dfnrq1 \mult_reg_reg[2]  (.CP(clk),
	.D(FE_PHN36_n_79),
	.Q(mult_reg[2]));
   ad01d1 g1162__2802 (.A(n_65),
	.B(n_53),
	.CI(n_63),
	.CO(n_80),
	.S(n_81));
   nd12d1 g1163__1705 (.A1(n_78),
	.A2(n_76),
	.ZN(n_82));
   oan211d1 g1164__5122 (.A(rst),
	.B(n_75),
	.C1(n_73),
	.C2(n_60),
	.ZN(n_79));
   an03d1 g1165__8246 (.A1(n_74),
	.A2(FE_PHN100_a_reg_3),
	.A3(FE_PHN98_b_reg_3),
	.Z(n_78));
   nd12d1 g1166__7098 (.A1(n_71),
	.A2(n_60),
	.ZN(n_77));
   nd02d1 g1167__6131 (.A1(n_73),
	.A2(n_60),
	.ZN(n_75));
   or02d1 g1168__1881 (.A1(n_74),
	.A2(FE_PHN98_b_reg_3),
	.Z(n_76));
   ad01d1 g1169__5115 (.A(n_47),
	.B(n_52),
	.CI(n_61),
	.CO(n_74),
	.S(n_72));
   ah01d1 g1170__7482 (.A(n_68),
	.B(n_50),
	.CO(n_71),
	.S(n_73));
   ad01d1 g1171__4733 (.A(n_46),
	.B(n_54),
	.CI(n_66),
	.CO(n_69),
	.S(n_70));
   dfnrq1 \mult_reg_reg[1]  (.CP(clk),
	.D(FE_PHN117_n_64),
	.Q(mult_reg[1]));
   ah01d1 g1173__6161 (.A(n_49),
	.B(n_56),
	.CO(n_67),
	.S(n_68));
   ah01d1 g1174__9315 (.A(n_48),
	.B(n_55),
	.CO(n_65),
	.S(n_66));
   an03d1 g1175__9945 (.A1(n_34),
	.A2(n_60),
	.A3(n_59),
	.Z(n_64));
   dfnrq1 \mult_reg_reg[0]  (.CP(clk),
	.D(n_62),
	.Q(mult_reg[0]));
   oai21d1 g1177__2883 (.A(n_61),
	.B1(n_33),
	.B2(n_58),
	.ZN(n_63));
   nr02d1 g1179__2346 (.A1(FE_PHN115_n_51),
	.A2(rst),
	.ZN(n_62));
   oai22d1 g1180__1666 (.A1(FE_PHN15_a_reg_1),
	.A2(FE_PHN14_b_reg_0),
	.B1(FE_PHN16_a_reg_0),
	.B2(FE_PHN13_b_reg_1),
	.ZN(n_59));
   nd02d1 g1181__7410 (.A1(n_33),
	.A2(n_58),
	.ZN(n_61));
   nd12d1 g1182__6417 (.A1(FE_PHN115_n_51),
	.A2(n_50),
	.ZN(n_60));
   nr02d1 g1183__5477 (.A1(FE_PHN64_enable_s1),
	.A2(rst),
	.ZN(n_57));
   nd02d1 g1184__2398 (.A1(n_45),
	.A2(n_44),
	.ZN(n_58));
   nr02d1 g1185__5107 (.A1(FE_PHN16_a_reg_0),
	.A2(FE_PHN97_b_reg_2),
	.ZN(n_56));
   nd12d1 g1186__6260 (.A1(FE_PHN14_b_reg_0),
	.A2(FE_PHN100_a_reg_3),
	.ZN(n_55));
   nd12d1 g1187__4319 (.A1(FE_PHN16_a_reg_0),
	.A2(FE_PHN98_b_reg_3),
	.ZN(n_54));
   nd12d1 g1188__8428 (.A1(FE_PHN15_a_reg_1),
	.A2(FE_PHN98_b_reg_3),
	.ZN(n_53));
   nd02d1 g1189__5526 (.A1(FE_PHN98_b_reg_3),
	.A2(n_44),
	.ZN(n_52));
   or02d1 g1191__6783 (.A1(FE_PHN16_a_reg_0),
	.A2(FE_PHN14_b_reg_0),
	.Z(n_51));
   nr02d1 g1192__3680 (.A1(FE_PHN99_a_reg_2),
	.A2(FE_PHN14_b_reg_0),
	.ZN(n_49));
   nr02d1 g1193__1617 (.A1(FE_PHN15_a_reg_1),
	.A2(FE_PHN13_b_reg_1),
	.ZN(n_50));
   nr02d1 g1194__2802 (.A1(FE_PHN99_a_reg_2),
	.A2(FE_PHN13_b_reg_1),
	.ZN(n_48));
   nd02d1 g1195__1705 (.A1(n_45),
	.A2(FE_PHN100_a_reg_3),
	.ZN(n_47));
   nr02d1 g1196__5122 (.A1(FE_PHN15_a_reg_1),
	.A2(FE_PHN97_b_reg_2),
	.ZN(n_46));
   dfnrn1 enable_s1_reg (.CP(clk),
	.D(FE_PHN52_n_40),
	.QN(enable_s1));
   dfnrn1 \b_reg_reg[1]  (.CP(clk),
	.D(FE_PHN50_n_41),
	.QN(b_reg[1]));
   dfnrn1 \a_reg_reg[1]  (.CP(clk),
	.D(FE_PHN37_n_36),
	.QN(a_reg[1]));
   dfnrq1 \b_reg_reg[3]  (.CP(clk),
	.D(FE_PHN49_n_37),
	.Q(b_reg[3]));
   dfnrn1 \a_reg_reg[0]  (.CP(clk),
	.D(FE_PHN45_n_38),
	.QN(a_reg[0]));
   dfnrq1 \a_reg_reg[3]  (.CP(clk),
	.D(FE_PHN47_n_43),
	.Q(a_reg[3]));
   dfnrn1 \b_reg_reg[0]  (.CP(clk),
	.D(FE_PHN48_n_39),
	.QN(b_reg[0]));
   an02d1 g1209__8246 (.A1(n_34),
	.A2(FE_PHN69_a_pad_3),
	.Z(n_43));
   an02d1 g1210__7098 (.A1(n_34),
	.A2(FE_PHN65_b_pad_2),
	.Z(n_42));
   an02d1 g1211__6131 (.A1(n_34),
	.A2(FE_PHN71_b_pad_1),
	.Z(n_41));
   an02d1 g1212__1881 (.A1(n_34),
	.A2(FE_PHN72_enable_pad),
	.Z(n_40));
   an02d1 g1213__5115 (.A1(n_34),
	.A2(FE_PHN70_b_pad_0),
	.Z(n_39));
   an02d1 g1214__7482 (.A1(n_34),
	.A2(FE_PHN67_a_pad_0),
	.Z(n_38));
   an02d1 g1215__4733 (.A1(n_34),
	.A2(FE_PHN66_b_pad_3),
	.Z(n_37));
   an02d1 g1216__6161 (.A1(n_34),
	.A2(FE_PHN73_a_pad_1),
	.Z(n_36));
   an02d1 g1217__9315 (.A1(n_34),
	.A2(FE_PHN68_a_pad_2),
	.Z(n_35));
   inv0d1 g1218 (.I(rst),
	.ZN(n_34));
   an12d1 g2__9945 (.A1(FE_PHN13_b_reg_1),
	.A2(FE_PHN100_a_reg_3),
	.Z(n_33));
   dfnrq1 \acc_reg_reg[7]  (.CP(clk),
	.D(FE_PHN33_n_31),
	.Q(mac_out[7]));
   dfnrq1 \acc_reg_reg[1]  (.CP(clk),
	.D(n_26),
	.Q(mac_out[1]));
   dfnrq1 \acc_reg_reg[5]  (.CP(clk),
	.D(FE_PHN23_n_17),
	.Q(mac_out[5]));
   dfnrq1 \acc_reg_reg[6]  (.CP(clk),
	.D(FE_PHN35_n_28),
	.Q(mac_out[6]));
   dfnrq1 \acc_reg_reg[0]  (.CP(clk),
	.D(n_32),
	.Q(mac_out[0]));
   dfnrq1 \acc_reg_reg[8]  (.CP(clk),
	.D(FE_PHN26_n_30),
	.Q(mac_out[8]));
   dfnrq1 \acc_reg_reg[9]  (.CP(clk),
	.D(FE_PHN39_n_29),
	.Q(mac_out[9]));
   dfnrq1 \acc_reg_reg[10]  (.CP(clk),
	.D(FE_PHN40_n_27),
	.Q(mac_out[10]));
   dfnrq1 \acc_reg_reg[14]  (.CP(clk),
	.D(FE_PHN29_n_24),
	.Q(mac_out[14]));
   dfnrq1 \acc_reg_reg[11]  (.CP(clk),
	.D(FE_PHN25_n_20),
	.Q(mac_out[11]));
   dfnrq1 \acc_reg_reg[12]  (.CP(clk),
	.D(FE_PHN43_n_23),
	.Q(mac_out[12]));
   dfnrq1 \acc_reg_reg[13]  (.CP(clk),
	.D(FE_PHN31_n_21),
	.Q(mac_out[13]));
   dfnrq1 \acc_reg_reg[2]  (.CP(clk),
	.D(FE_PHN32_n_25),
	.Q(mac_out[2]));
   dfnrq1 \acc_reg_reg[3]  (.CP(clk),
	.D(FE_PHN34_n_22),
	.Q(mac_out[3]));
   dfnrq1 \acc_reg_reg[15]  (.CP(clk),
	.D(FE_PHN24_n_19),
	.Q(mac_out[15]));
   dfnrq1 \acc_reg_reg[4]  (.CP(clk),
	.D(FE_PHN27_n_18),
	.Q(FE_OFN11_mac_out_pad_4));
   nr02d1 g662__2883 (.A1(FE_PHN113_n_13),
	.A2(rst),
	.ZN(n_32));
   nr02d1 g663__2346 (.A1(FE_PHN76_n_15),
	.A2(rst),
	.ZN(n_31));
   nr02d1 g664__1666 (.A1(FE_PHN84_n_14),
	.A2(rst),
	.ZN(n_30));
   nr02d1 g665__7410 (.A1(FE_PHN81_n_16),
	.A2(rst),
	.ZN(n_29));
   nr02d1 g666__6417 (.A1(FE_PHN91_n_12),
	.A2(rst),
	.ZN(n_28));
   nr02d1 g667__5477 (.A1(FE_PHN74_n_10),
	.A2(rst),
	.ZN(n_27));
   nr02d1 g668__2398 (.A1(FE_PHN114_n_11),
	.A2(rst),
	.ZN(n_26));
   nr02d1 g669__5107 (.A1(FE_PHN90_n_5),
	.A2(rst),
	.ZN(n_25));
   nr02d1 g670__6260 (.A1(FE_PHN89_n_8),
	.A2(rst),
	.ZN(n_24));
   nr02d1 g671__4319 (.A1(FE_PHN75_n_4),
	.A2(rst),
	.ZN(n_23));
   nr02d1 g672__8428 (.A1(FE_PHN85_n_6),
	.A2(rst),
	.ZN(n_22));
   nr02d1 g673__5526 (.A1(FE_PHN80_n_7),
	.A2(rst),
	.ZN(n_21));
   nr02d1 g674__6783 (.A1(FE_PHN82_n_9),
	.A2(rst),
	.ZN(n_20));
   nr02d1 g675__3680 (.A1(FE_PHN92_n_3),
	.A2(rst),
	.ZN(n_19));
   nr02d1 g676__1617 (.A1(FE_PHN93_n_2),
	.A2(rst),
	.ZN(n_18));
   nr02d1 g677__2802 (.A1(FE_PHN88_n_1),
	.A2(rst),
	.ZN(n_17));
   aoi22d1 g678__1705 (.A1(mac_out[9]),
	.A2(FE_PHN17_n_0),
	.B1(n_110),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_16));
   aoi22d1 g679__5122 (.A1(mac_out[7]),
	.A2(FE_PHN17_n_0),
	.B1(n_112),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_15));
   aoi22d1 g680__8246 (.A1(mac_out[8]),
	.A2(FE_PHN17_n_0),
	.B1(n_111),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_14));
   aoi22d1 g681__7098 (.A1(FE_PHN60_mac_out_pad_0),
	.A2(FE_PHN17_n_0),
	.B1(n_119),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_13));
   aoi22d1 g682__6131 (.A1(mac_out[6]),
	.A2(FE_PHN17_n_0),
	.B1(n_113),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_12));
   aoi22d1 g683__1881 (.A1(FE_PHN59_mac_out_pad_1),
	.A2(FE_PHN17_n_0),
	.B1(n_118),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_11));
   aoi22d1 g684__5115 (.A1(mac_out[10]),
	.A2(FE_PHN17_n_0),
	.B1(n_109),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_10));
   aoi22d1 g685__7482 (.A1(mac_out[11]),
	.A2(FE_PHN17_n_0),
	.B1(n_108),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_9));
   aoi22d1 g686__4733 (.A1(mac_out[14]),
	.A2(FE_PHN17_n_0),
	.B1(n_105),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_8));
   aoi22d1 g687__6161 (.A1(mac_out[13]),
	.A2(FE_PHN17_n_0),
	.B1(n_106),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_7));
   aoi22d1 g688__9315 (.A1(FE_PHN102_mac_out_pad_3),
	.A2(FE_PHN17_n_0),
	.B1(n_116),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_6));
   aoi22d1 g689__9945 (.A1(FE_PHN101_mac_out_pad_2),
	.A2(FE_PHN17_n_0),
	.B1(n_117),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_5));
   aoi22d1 g690__2883 (.A1(mac_out[12]),
	.A2(FE_PHN17_n_0),
	.B1(n_107),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_4));
   aoi22d1 g691__2346 (.A1(mac_out[15]),
	.A2(FE_PHN17_n_0),
	.B1(n_122),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_3));
   aoi22d1 g692__1666 (.A1(mac_out[4]),
	.A2(FE_PHN17_n_0),
	.B1(n_115),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_2));
   aoi22d1 g693__7410 (.A1(mac_out[5]),
	.A2(FE_PHN17_n_0),
	.B1(n_114),
	.B2(FE_PHN18_enable_s2),
	.ZN(n_1));
   ad01d1 add_89_32_g369__5477 (.A(mac_out[14]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_28),
	.CO(add_89_32_n_31),
	.S(n_105));
   ad01d1 add_89_32_g370__2398 (.A(mac_out[13]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_26),
	.CO(add_89_32_n_28),
	.S(n_106));
   ad01d1 add_89_32_g371__5107 (.A(mac_out[12]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_24),
	.CO(add_89_32_n_26),
	.S(n_107));
   ad01d1 add_89_32_g372__6260 (.A(mac_out[11]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_22),
	.CO(add_89_32_n_24),
	.S(n_108));
   ad01d1 add_89_32_g373__4319 (.A(mac_out[10]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_20),
	.CO(add_89_32_n_22),
	.S(n_109));
   ad01d1 add_89_32_g374__8428 (.A(mac_out[9]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_18),
	.CO(add_89_32_n_20),
	.S(n_110));
   ad01d1 add_89_32_g375__5526 (.A(mac_out[8]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_16),
	.CO(add_89_32_n_18),
	.S(n_111));
   ad01d1 add_89_32_g376__6783 (.A(mac_out[7]),
	.B(FE_PHN63_mult_reg_7),
	.CI(add_89_32_n_14),
	.CO(add_89_32_n_16),
	.S(n_112));
   ad01d1 add_89_32_g377__3680 (.A(mac_out[6]),
	.B(mult_reg[6]),
	.CI(add_89_32_n_12),
	.CO(add_89_32_n_14),
	.S(n_113));
   ad01d1 add_89_32_g378__1617 (.A(mac_out[5]),
	.B(mult_reg[5]),
	.CI(add_89_32_n_10),
	.CO(add_89_32_n_12),
	.S(n_114));
   ad01d1 add_89_32_g379__2802 (.A(mac_out[4]),
	.B(FE_PHN96_mult_reg_4),
	.CI(add_89_32_n_8),
	.CO(add_89_32_n_10),
	.S(n_115));
   ad01d1 add_89_32_g380__1705 (.A(FE_PHN102_mac_out_pad_3),
	.B(FE_PHN95_mult_reg_3),
	.CI(add_89_32_n_6),
	.CO(add_89_32_n_8),
	.S(n_116));
   ad01d1 add_89_32_g381__5122 (.A(FE_PHN101_mac_out_pad_2),
	.B(FE_PHN94_mult_reg_2),
	.CI(add_89_32_n_4),
	.CO(add_89_32_n_6),
	.S(n_117));
   ad01d1 add_89_32_g382__8246 (.A(FE_PHN59_mac_out_pad_1),
	.B(FE_PHN21_mult_reg_1),
	.CI(add_89_32_n_2),
	.CO(add_89_32_n_4),
	.S(n_118));
   ah01d1 add_89_32_g383__7098 (.A(FE_PHN60_mac_out_pad_0),
	.B(FE_PHN22_mult_reg_0),
	.CO(add_89_32_n_2),
	.S(n_119));
   xr03d1 g2 (.A1(add_89_32_n_31),
	.A2(mac_out[15]),
	.A3(FE_PHN63_mult_reg_7),
	.Z(n_122));
   dfnrb1 \b_reg_reg[2]  (.CP(clk),
	.D(FE_PHN51_n_42),
	.Q(n_45),
	.QN(b_reg[2]));
   dfnrb1 \a_reg_reg[2]  (.CP(clk),
	.D(FE_PHN38_n_35),
	.Q(n_44),
	.QN(a_reg[2]));
   dfnrb1 enable_s2_reg (.CP(clk),
	.D(FE_PHN46_n_57),
	.Q(enable_s2),
	.QN(n_0));
endmodule

module mac_4x4_wrapper_chip (
	clk, 
	rst, 
	enable, 
	a, 
	b, 
	mac_out);
   input clk;
   input rst;
   input enable;
   input [3:0] a;
   input [3:0] b;
   output [15:0] mac_out;

   // Internal wires
   wire FE_PHN111_b_pad_3;
   wire FE_PHN110_b_pad_0;
   wire FE_PHN109_b_pad_2;
   wire FE_PHN108_enable_pad;
   wire FE_PHN107_b_pad_1;
   wire FE_PHN106_a_pad_0;
   wire FE_PHN105_a_pad_3;
   wire FE_PHN104_a_pad_1;
   wire FE_PHN103_a_pad_2;
   wire FE_PHN12_rst_pad;
   wire FE_OFN13_mac_out_pad_15;
   wire FE_OFN12_mac_out_pad_14;
   wire FE_OFN10_mac_out_pad_5;
   wire FE_OFN9_mac_out_pad_6;
   wire FE_OFN8_mac_out_pad_7;
   wire FE_OFN7_mac_out_pad_8;
   wire FE_OFN6_mac_out_pad_9;
   wire FE_OFN5_mac_out_pad_10;
   wire FE_OFN4_mac_out_pad_11;
   wire FE_OFN3_mac_out_pad_12;
   wire FE_OFN2_mac_out_pad_13;
   wire [3:0] a_pad;
   wire [3:0] b_pad;
   wire [15:0] mac_out_pad;
   wire clk_buf;
   wire clk_pad;
   wire enable_pad;
   wire rst_pad;
   wire VDD_CORE;
   wire VSS_CORE;
   wire VDDO_CORE;
   wire VSSO_CORE;

   dl04d1 FE_PHC111_b_pad_3 (.I(b_pad[3]),
	.Z(FE_PHN111_b_pad_3));
   dl04d1 FE_PHC110_b_pad_0 (.I(b_pad[0]),
	.Z(FE_PHN110_b_pad_0));
   dl04d1 FE_PHC109_b_pad_2 (.I(b_pad[2]),
	.Z(FE_PHN109_b_pad_2));
   dl04d1 FE_PHC108_enable_pad (.I(enable_pad),
	.Z(FE_PHN108_enable_pad));
   dl04d1 FE_PHC107_b_pad_1 (.I(b_pad[1]),
	.Z(FE_PHN107_b_pad_1));
   dl04d1 FE_PHC106_a_pad_0 (.I(a_pad[0]),
	.Z(FE_PHN106_a_pad_0));
   dl04d1 FE_PHC105_a_pad_3 (.I(a_pad[3]),
	.Z(FE_PHN105_a_pad_3));
   dl04d1 FE_PHC104_a_pad_1 (.I(a_pad[1]),
	.Z(FE_PHN104_a_pad_1));
   dl04d1 FE_PHC103_a_pad_2 (.I(a_pad[2]),
	.Z(FE_PHN103_a_pad_2));
   dl04d2 FE_PHC12_rst_pad (.I(rst_pad),
	.Z(FE_PHN12_rst_pad));
   buffd1 FE_OFC13_mac_out_pad_15 (.I(mac_out_pad[15]),
	.Z(FE_OFN13_mac_out_pad_15));
   buffd1 FE_OFC12_mac_out_pad_14 (.I(mac_out_pad[14]),
	.Z(FE_OFN12_mac_out_pad_14));
   buffd1 FE_OFC10_mac_out_pad_5 (.I(mac_out_pad[5]),
	.Z(FE_OFN10_mac_out_pad_5));
   buffd1 FE_OFC9_mac_out_pad_6 (.I(mac_out_pad[6]),
	.Z(FE_OFN9_mac_out_pad_6));
   buffd1 FE_OFC8_mac_out_pad_7 (.I(mac_out_pad[7]),
	.Z(FE_OFN8_mac_out_pad_7));
   buffd1 FE_OFC7_mac_out_pad_8 (.I(mac_out_pad[8]),
	.Z(FE_OFN7_mac_out_pad_8));
   buffd1 FE_OFC6_mac_out_pad_9 (.I(mac_out_pad[9]),
	.Z(FE_OFN6_mac_out_pad_9));
   buffd1 FE_OFC5_mac_out_pad_10 (.I(mac_out_pad[10]),
	.Z(FE_OFN5_mac_out_pad_10));
   buffd3 FE_OFC4_mac_out_pad_11 (.I(mac_out_pad[11]),
	.Z(FE_OFN4_mac_out_pad_11));
   buffd1 FE_OFC3_mac_out_pad_12 (.I(mac_out_pad[12]),
	.Z(FE_OFN3_mac_out_pad_12));
   buffd1 FE_OFC2_mac_out_pad_13 (.I(mac_out_pad[13]),
	.Z(FE_OFN2_mac_out_pad_13));
   mac_4x4 dut (.clk(clk_buf),
	.rst(FE_PHN12_rst_pad),
	.enable(FE_PHN108_enable_pad),
	.a({ FE_PHN105_a_pad_3,
		FE_PHN103_a_pad_2,
		FE_PHN104_a_pad_1,
		FE_PHN106_a_pad_0 }),
	.b({ FE_PHN111_b_pad_3,
		FE_PHN109_b_pad_2,
		FE_PHN107_b_pad_1,
		FE_PHN110_b_pad_0 }),
	.mac_out(mac_out_pad));
   pc3c01 pc3c01_clk_buf (.CCLK(clk_pad),
	.CP(clk_buf));
   pc3d01 pc3d01_a0 (.PAD(a[0]),
	.CIN(a_pad[0]));
   pc3d01 pc3d01_a1 (.PAD(a[1]),
	.CIN(a_pad[1]));
   pc3d01 pc3d01_a2 (.PAD(a[2]),
	.CIN(a_pad[2]));
   pc3d01 pc3d01_a3 (.PAD(a[3]),
	.CIN(a_pad[3]));
   pc3d01 pc3d01_b0 (.PAD(b[0]),
	.CIN(b_pad[0]));
   pc3d01 pc3d01_b1 (.PAD(b[1]),
	.CIN(b_pad[1]));
   pc3d01 pc3d01_b2 (.PAD(b[2]),
	.CIN(b_pad[2]));
   pc3d01 pc3d01_b3 (.PAD(b[3]),
	.CIN(b_pad[3]));
   pc3d01 pc3d01_clk (.PAD(clk),
	.CIN(clk_pad));
   pc3d01 pc3d01_enable (.PAD(enable),
	.CIN(enable_pad));
   pc3d01 pc3d01_rst (.PAD(rst),
	.CIN(rst_pad));
   pc3o01 pc3o01_mac_out0 (.I(mac_out_pad[0]),
	.PAD(mac_out[0]));
   pc3o01 pc3o01_mac_out1 (.I(mac_out_pad[1]),
	.PAD(mac_out[1]));
   pc3o01 pc3o01_mac_out2 (.I(mac_out_pad[2]),
	.PAD(mac_out[2]));
   pc3o01 pc3o01_mac_out3 (.I(mac_out_pad[3]),
	.PAD(mac_out[3]));
   pc3o01 pc3o01_mac_out4 (.I(mac_out_pad[4]),
	.PAD(mac_out[4]));
   pc3o01 pc3o01_mac_out5 (.I(FE_OFN10_mac_out_pad_5),
	.PAD(mac_out[5]));
   pc3o01 pc3o01_mac_out6 (.I(FE_OFN9_mac_out_pad_6),
	.PAD(mac_out[6]));
   pc3o01 pc3o01_mac_out7 (.I(FE_OFN8_mac_out_pad_7),
	.PAD(mac_out[7]));
   pc3o01 pc3o01_mac_out8 (.I(FE_OFN7_mac_out_pad_8),
	.PAD(mac_out[8]));
   pc3o01 pc3o01_mac_out9 (.I(FE_OFN6_mac_out_pad_9),
	.PAD(mac_out[9]));
   pc3o01 pc3o01_mac_out10 (.I(FE_OFN5_mac_out_pad_10),
	.PAD(mac_out[10]));
   pc3o01 pc3o01_mac_out11 (.I(FE_OFN4_mac_out_pad_11),
	.PAD(mac_out[11]));
   pc3o01 pc3o01_mac_out12 (.I(FE_OFN3_mac_out_pad_12),
	.PAD(mac_out[12]));
   pc3o01 pc3o01_mac_out13 (.I(FE_OFN2_mac_out_pad_13),
	.PAD(mac_out[13]));
   pc3o01 pc3o01_mac_out14 (.I(FE_OFN12_mac_out_pad_14),
	.PAD(mac_out[14]));
   pc3o01 pc3o01_mac_out15 (.I(FE_OFN13_mac_out_pad_15),
	.PAD(mac_out[15]));
   pc3o01 pc3o01_dummy1 ();
   pc3o01 pc3o01_dummy2 ();
   pc3o01 pc3o01_dummy3 ();
   pc3o01 pc3o01_dummy4 ();
   pvdi pvdi_VDD_0 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_0 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvda pvda_VDDO_0 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_0 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_1 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_1 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvda pvda_VDDO_1 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_1 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_2 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_2 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvda pvda_VDDO_2 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_2 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_3 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_3 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pvda pvda_VDDO_3 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_3 (.VSSO(VSSO_CORE),
	.VSS(VSS_CORE),
	.VDDO(VDDO_CORE),
	.VDD(VDD_CORE));
endmodule

